### ISSUE TITLE
java jdbc 8.0.x 读不到文件

### ISSUE THREAD

**Issue by handbye** [rmb122/rogue_mysql_server#8]
报错信息如下“

```java
Exception in thread "main" java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/* mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout' at line 1
 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
 at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
 at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
 at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
 at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
 at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
 at java.sql.DriverManager.getConnection(DriverManager.java:664)
 at java.sql.DriverManager.getConnection(DriverManager.java:247)
 at Test.main(Test.java:12)
```

服务端日志如下，可以看到连接信息，但是读不到文件
![image](https://user-images.githubusercontent.com/26617058/150058024-d1729d9d-6369-4af6-896f-d1d0481e96f9.png)

**Comment by rmb122** [comment]
8.0.17 allowLoadLocalInfile 默认是 false, https://github.com/mysql/mysql-connector-j/blob/7ff2161da3/src/main/core-api/java/com/mysql/cj/conf/PropertyDefinitions.java#L370
你需要在 connection string 里面设置 allowLoadLocalInfile=true, 可以参考
https://github.com/rmb122/rogue_mysql_server/blob/master/test/java/src/main/java/com/rmb122/App.java#L13
